-- V1 Migration 003
-- Purpose:
--   Create task suggestion, review, formal task, and operation plan tables.

CREATE TABLE IF NOT EXISTS cf_calendar_item (
  id bigserial PRIMARY KEY,
  planting_plan_id bigint NOT NULL REFERENCES cf_planting_plan(id) ON DELETE CASCADE,
  stage_code varchar(50),
  task_category varchar(50) NOT NULL,
  task_subtype varchar(100) NOT NULL,
  title varchar(255) NOT NULL,
  description text,
  suggested_start_date date NOT NULL,
  suggested_end_date date NOT NULL,
  status varchar(50) NOT NULL DEFAULT 'active',
  calendar_version int4 NOT NULL DEFAULT 1,
  source_snapshot_id bigint REFERENCES cf_stage_prediction_snapshot(id) ON DELETE SET NULL,
  parent_task_id bigint,
  source_execution_id bigint,
  source_execution_record_id bigint,
  generation_condition jsonb NOT NULL DEFAULT '{}'::jsonb,
  generated_task_id bigint,
  last_generation_checked_at timestamp,
  invalidated_reason text,
  idempotency_key varchar(255) NOT NULL,
  created_by_type varchar(20) NOT NULL DEFAULT 'system',
  created_by_id varchar(100),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cf_calendar_item_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS cf_task_intent (
  id bigserial PRIMARY KEY,
  planting_plan_id bigint NOT NULL REFERENCES cf_planting_plan(id) ON DELETE CASCADE,
  task_category varchar(50) NOT NULL,
  task_subtype varchar(100) NOT NULL,
  priority varchar(20) NOT NULL DEFAULT 'normal',
  status varchar(50) NOT NULL DEFAULT 'pending',
  trigger_type varchar(50) NOT NULL,
  trigger_summary text,
  rule_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  suggested_action text,
  need_more_info_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  no_action_reason text,
  parent_task_id bigint,
  source_execution_id bigint,
  source_execution_record_id bigint,
  converted_task_id bigint,
  source_event_id bigint REFERENCES cf_event_record(id) ON DELETE SET NULL,
  idempotency_key varchar(255) NOT NULL,
  created_by_type varchar(20) NOT NULL DEFAULT 'system',
  created_by_id varchar(100),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cf_task_intent_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS cf_review_request (
  id bigserial PRIMARY KEY,
  planting_plan_id bigint NOT NULL REFERENCES cf_planting_plan(id) ON DELETE CASCADE,
  review_type varchar(50) NOT NULL,
  status varchar(50) NOT NULL DEFAULT 'open',
  priority varchar(20) NOT NULL DEFAULT 'normal',
  assigned_user_id varchar(100) REFERENCES cf_user(id) ON DELETE SET NULL,
  source_entity_type varchar(100) NOT NULL,
  source_entity_id bigint NOT NULL,
  title varchar(255) NOT NULL,
  description text,
  decision varchar(50),
  decision_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolved_by varchar(100) REFERENCES cf_user(id) ON DELETE SET NULL,
  resolved_at timestamp,
  idempotency_key varchar(255) NOT NULL,
  created_by_type varchar(20) NOT NULL DEFAULT 'system',
  created_by_id varchar(100),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cf_review_request_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS cf_farming_task (
  id bigserial PRIMARY KEY,
  planting_plan_id bigint NOT NULL REFERENCES cf_planting_plan(id) ON DELETE CASCADE,
  calendar_item_id bigint REFERENCES cf_calendar_item(id) ON DELETE SET NULL,
  task_intent_id bigint REFERENCES cf_task_intent(id) ON DELETE SET NULL,
  review_request_id bigint REFERENCES cf_review_request(id) ON DELETE SET NULL,
  task_category varchar(50) NOT NULL,
  task_subtype varchar(100) NOT NULL,
  title varchar(255) NOT NULL,
  description text,
  target_stage_code varchar(50),
  planned_start_at timestamp,
  planned_end_at timestamp,
  priority varchar(20) NOT NULL DEFAULT 'normal',
  status varchar(50) NOT NULL DEFAULT 'pending',
  execution_mode varchar(50) NOT NULL DEFAULT 'manual',
  generation_reason text,
  parent_task_id bigint,
  source_execution_id bigint,
  source_execution_record_id bigint,
  idempotency_key varchar(255) NOT NULL,
  created_by_type varchar(20) NOT NULL DEFAULT 'system',
  created_by_id varchar(100),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cf_farming_task_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS cf_operation_plan (
  id bigserial PRIMARY KEY,
  planting_plan_id bigint NOT NULL REFERENCES cf_planting_plan(id) ON DELETE CASCADE,
  farming_task_id bigint NOT NULL REFERENCES cf_farming_task(id) ON DELETE CASCADE,
  plan_type varchar(50) NOT NULL,
  status varchar(50) NOT NULL DEFAULT 'draft',
  version int4 NOT NULL DEFAULT 1,
  algorithm_code varchar(100),
  algorithm_version varchar(100),
  operation_area jsonb NOT NULL DEFAULT '{}'::jsonb,
  operation_window_start timestamp,
  operation_window_end timestamp,
  execution_mode varchar(50) NOT NULL DEFAULT 'manual',
  parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
  prescription_map jsonb NOT NULL DEFAULT '{}'::jsonb,
  acceptance_criteria jsonb NOT NULL DEFAULT '{}'::jsonb,
  basis text,
  source_event_id bigint REFERENCES cf_event_record(id) ON DELETE SET NULL,
  idempotency_key varchar(255) NOT NULL,
  created_by_type varchar(20) NOT NULL DEFAULT 'system',
  created_by_id varchar(100),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cf_operation_plan_idempotency_key UNIQUE (idempotency_key)
);
