from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import UTC, date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import select, text
from sqlalchemy.orm import Session

from app.db.session import get_session_factory
from app.models import CalendarItem, Farm, FarmingTask, Field, ReviewRequest, TaskIntent, User
from app.orchestrator import build_plan_orchestrator
from app.repositories import (
    CalendarItemRepository,
    CodeDictRepository,
    CropStageDictRepository,
    CropStageStateRepository,
    CropThermalTimeStateRepository,
    EventRecordRepository,
    ExecutionRecordRepository,
    ExecutionRepository,
    FarmRepository,
    FieldRepository,
    FarmingTaskRepository,
    OperationPlanRepository,
    PlantingPlanFieldRelationRepository,
    PlantingPlanRepository,
    RiceControlWindowLevel1Repository,
    RiceVarietyRepository,
    ReviewRequestRepository,
    StagePredictionSnapshotRepository,
    TaskIntentRepository,
)
from app.services import (
    MockPestDiseaseControlClient,
    MockPestDiseaseSurveyWindowClient,
    MockStagePredictionClient,
    MockWeatherProvider,
    MockWeedDiagnosisClient,
    PestDiseaseControlPlanningService,
    PlantingPlanCreateInput,
    PlantingPlanService,
    PlantProtectionPlanContextResolver,
    StageManagementService,
    SurveyDateRecommendationService,
    SurveyResultService,
    TaskGenerationService,
)

SEED_ACTOR = "bootstrap_review_adjustment_demo"


@dataclass(slots=True)
class ReviewSummary:
    id: int
    review_type: str
    task_subtype: str | None
    title: str
    status: str


@dataclass(slots=True)
class BootstrapSummary:
    planting_plan_id: int
    plan_code: str
    plan_name: str
    farm_id: int
    field_ids: list[int]
    generated_task_ids: list[int]
    open_reviews: list[ReviewSummary]


def main() -> None:
    session_factory = get_session_factory()
    with session_factory() as session:
        summary = bootstrap_review_adjustment_demo(session)
        session.commit()

    print(json.dumps(_serialize_summary(summary), ensure_ascii=False, indent=2))


def bootstrap_review_adjustment_demo(session: Session) -> BootstrapSummary:
    farm_id = _ensure_demo_farm(session)
    field_ids = _ensure_demo_fields(session, farm_id=farm_id)
    _ensure_demo_reviewer(session)

    services = _build_services(session)
    plan_code = f"REVIEW-ADJUST-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}"
    plan_name = "审核修改联调样板计划"
    plan_details = services.planting_plan_service.create(
        PlantingPlanCreateInput(
            plan_code=plan_code,
            plan_name=plan_name,
            farm_id=farm_id,
            field_ids=field_ids,
            culti_type_code=5,
            planting_method_code=1,
            crop_name="水稻",
            variety_id=1,
            sowing_date=date(2026, 4, 10),
            status="active",
            task_generation_window_days=14,
            metadata_payload={
                "seed": True,
                "province": "湖南省",
                "pestDisease": {
                    "growth_stage": {
                        "tillering_date": "2026-04-20",
                        "pokou_date": "2026-06-10",
                        "heading_date": "2026-06-18",
                        "maturity_date": "2026-07-20",
                    },
                },
                "notes": "Generated by bootstrap_review_adjustment_demo.py for review adjustment testing.",
            },
        ),
    )
    planting_plan_id = int(plan_details.planting_plan.id)
    session.flush()

    services.survey_date_service.recommend_regular_disease_pest_surveys(planting_plan_id)
    session.flush()

    calendar_items = list(
        session.scalars(
            select(CalendarItem)
            .where(CalendarItem.planting_plan_id == planting_plan_id)
            .order_by(CalendarItem.suggested_start_date.asc(), CalendarItem.id.asc()),
        ),
    )
    pre_survey_item = next(
        item for item in calendar_items if item.task_subtype == "plant_protection.stem_leaf_weed_pre_survey"
    )
    regular_survey_item = next(
        item for item in calendar_items if item.task_subtype == "plant_protection.regular_disease_pest_survey"
    )

    generated_task_ids: list[int] = []
    for check_date in sorted({pre_survey_item.suggested_start_date, regular_survey_item.suggested_start_date}):
        generated_task_ids.extend(
            task.id
            for task in services.task_generation_service.generate_due_tasks(
                planting_plan_id,
                check_date=check_date,
            )
        )

    tasks = list(
        session.scalars(
            select(FarmingTask)
            .where(FarmingTask.planting_plan_id == planting_plan_id)
            .order_by(FarmingTask.id.asc()),
        ),
    )
    pre_survey_task = next(item for item in tasks if item.task_subtype == "plant_protection.stem_leaf_weed_pre_survey")
    regular_survey_task = next(
        item for item in tasks if item.task_subtype == "plant_protection.regular_disease_pest_survey"
    )

    services.survey_result_service.record_survey_result(
        pre_survey_task.id,
        {
            "province": "湖南省",
            "survey_date": "20260418",
            "rice_leaf_age": 4.5,
            "BaiCao": {"leaf_age": 2, "mass": 100},
            "QianJinZi": {"leaf_age": 0, "mass": 0},
            "KuoYeCao": {"mass": 0},
            "SuoCao": {"mass": 0},
        },
    )
    session.flush()
    services.survey_result_service.record_survey_result(
        regular_survey_task.id,
        {
            "survey_date": "20260628",
            "survey_method": "一级理论防治日期",
            "bbch_stage": 23,
            "DaoFeiShi": {"insects_per_100_hills": 12},
        },
    )
    session.flush()

    open_reviews = _list_open_reviews(session, planting_plan_id)
    if not open_reviews:
        raise RuntimeError("No open review requests were generated.")

    return BootstrapSummary(
        planting_plan_id=planting_plan_id,
        plan_code=plan_code,
        plan_name=plan_name,
        farm_id=farm_id,
        field_ids=field_ids,
        generated_task_ids=generated_task_ids,
        open_reviews=open_reviews,
    )


@dataclass(slots=True)
class ServiceBundle:
    planting_plan_service: PlantingPlanService
    survey_date_service: SurveyDateRecommendationService
    task_generation_service: TaskGenerationService
    survey_result_service: SurveyResultService


def _build_services(session: Session) -> ServiceBundle:
    planting_plan_repository = PlantingPlanRepository(session)
    event_record_repository = EventRecordRepository(session)
    calendar_item_repository = CalendarItemRepository(session)
    farming_task_repository = FarmingTaskRepository(session)
    review_request_repository = ReviewRequestRepository(session)
    task_intent_repository = TaskIntentRepository(session)
    operation_plan_repository = OperationPlanRepository(session)

    weather_provider = MockWeatherProvider()
    diagnosis_client = MockWeedDiagnosisClient()
    pest_disease_survey_client = MockPestDiseaseSurveyWindowClient()
    pest_disease_control_client = MockPestDiseaseControlClient()

    survey_date_service = SurveyDateRecommendationService(
        planting_plan_repository=planting_plan_repository,
        farm_repository=FarmRepository(session),
        rice_variety_repository=RiceVarietyRepository(session),
        code_dict_repository=CodeDictRepository(session),
        rice_control_window_level1_repository=RiceControlWindowLevel1Repository(session),
        calendar_item_repository=calendar_item_repository,
        event_record_repository=event_record_repository,
        weather_provider=weather_provider,
        diagnosis_client=diagnosis_client,
        pest_disease_client=pest_disease_survey_client,
        stage_prediction_snapshot_repository=StagePredictionSnapshotRepository(session),
        farming_task_repository=farming_task_repository,
    )
    stage_management_service = StageManagementService(
        planting_plan_repository=planting_plan_repository,
        farm_repository=FarmRepository(session),
        rice_variety_repository=RiceVarietyRepository(session),
        stage_prediction_snapshot_repository=StagePredictionSnapshotRepository(session),
        crop_stage_state_repository=CropStageStateRepository(session),
        crop_thermal_time_state_repository=CropThermalTimeStateRepository(session),
        stage_prediction_client=MockStagePredictionClient(),
        weather_provider=weather_provider,
        crop_stage_dict_repository=CropStageDictRepository(session),
    )
    context_resolver = PlantProtectionPlanContextResolver(
        code_dict_repository=CodeDictRepository(session),
        rice_variety_repository=RiceVarietyRepository(session),
    )
    pest_disease_control_planning_service = PestDiseaseControlPlanningService(
        planting_plan_repository=planting_plan_repository,
        farm_repository=FarmRepository(session),
        rice_control_window_level1_repository=RiceControlWindowLevel1Repository(session),
        stage_prediction_snapshot_repository=StagePredictionSnapshotRepository(session),
        calendar_item_repository=calendar_item_repository,
        operation_plan_repository=operation_plan_repository,
        context_resolver=context_resolver,
        weather_provider=weather_provider,
        control_client=pest_disease_control_client,
    )
    plan_orchestrator = build_plan_orchestrator(
        planting_plan_repository=planting_plan_repository,
        calendar_item_repository=calendar_item_repository,
        farming_task_repository=farming_task_repository,
        event_record_repository=event_record_repository,
        task_intent_repository=task_intent_repository,
        review_request_repository=review_request_repository,
        operation_plan_repository=operation_plan_repository,
        stage_management_service=stage_management_service,
        survey_date_recommendation_service=survey_date_service,
        weather_provider=weather_provider,
        diagnosis_client=diagnosis_client,
        context_resolver=context_resolver,
        pest_disease_control_planning_service=pest_disease_control_planning_service,
    )

    return ServiceBundle(
        planting_plan_service=PlantingPlanService(
            planting_plan_repository=planting_plan_repository,
            field_repository=FieldRepository(session),
            planting_plan_field_relation_repository=PlantingPlanFieldRelationRepository(session),
            rice_variety_repository=RiceVarietyRepository(session),
            farm_repository=FarmRepository(session),
            event_record_repository=event_record_repository,
            plan_orchestrator=plan_orchestrator,
        ),
        survey_date_service=survey_date_service,
        task_generation_service=TaskGenerationService(
            planting_plan_repository=planting_plan_repository,
            event_record_repository=event_record_repository,
            plan_orchestrator=plan_orchestrator,
        ),
        survey_result_service=SurveyResultService(
            farming_task_repository=farming_task_repository,
            execution_repository=ExecutionRepository(session),
            execution_record_repository=ExecutionRecordRepository(session),
            event_record_repository=event_record_repository,
            plan_orchestrator=plan_orchestrator,
        ),
    )


def _ensure_demo_farm(session: Session) -> int:
    farm = session.get(Farm, 1)
    if farm is None:
        farm = Farm(id=1)
        session.add(farm)

    farm.farm_name = "本地联调农场"
    farm.province = "湖南省"
    farm.city = "长沙市"
    farm.district_county = "望城区"
    farm.adcode = "430112"
    farm.centroid_lat = Decimal("28.143803")
    farm.centroid_lon = Decimal("112.811371")
    farm.created_by_type = "system"
    farm.created_by_id = SEED_ACTOR
    session.flush()
    _sync_id_sequence(session, "cf_farm")
    return int(farm.id)


def _ensure_demo_fields(session: Session, *, farm_id: int) -> list[int]:
    field_specs = [
        (10, "联调田块 A", Decimal("1.2500"), Decimal("28.194180"), Decimal("112.982310")),
        (11, "联调田块 B", Decimal("0.9800"), Decimal("28.193940"), Decimal("112.982020")),
    ]
    field_ids: list[int] = []
    for field_id, field_name, area_ha, centroid_lat, centroid_lon in field_specs:
        field = session.get(Field, field_id)
        if field is None:
            field = Field(id=field_id)
            session.add(field)
        field.field_name = field_name
        field.area_ha = area_ha
        field.centroid_lat = centroid_lat
        field.centroid_lon = centroid_lon
        field.created_by_type = "system"
        field.created_by_id = SEED_ACTOR
        field_ids.append(field_id)

    session.flush()
    _sync_id_sequence(session, "cf_field")

    for field_id in field_ids:
        exists = session.execute(
            text("select 1 from cf_farm_field_relation where farm_id = :farm_id and field_id = :field_id"),
            {"farm_id": farm_id, "field_id": field_id},
        ).scalar_one_or_none()
        if exists:
            continue
        session.execute(
            text(
                """
                insert into cf_farm_field_relation (farm_id, field_id, created_by_type, created_by_id)
                values (:farm_id, :field_id, 'system', :created_by_id)
                """
            ),
            {"farm_id": farm_id, "field_id": field_id, "created_by_id": SEED_ACTOR},
        )

    return field_ids


def _ensure_demo_reviewer(session: Session) -> None:
    reviewer = session.get(User, "reviewer-demo")
    if reviewer is None:
        reviewer = User(id="reviewer-demo")
        session.add(reviewer)

    reviewer.user_code = "reviewer-demo"
    reviewer.username = "reviewer-demo"
    reviewer.display_name = "联调复核员"
    reviewer.mobile = "13800000000"
    reviewer.email = "reviewer-demo@cropflow.local"
    reviewer.status = "active"
    reviewer.metadata_payload = {"seed": True}
    reviewer.created_by_type = "system"
    reviewer.created_by_id = SEED_ACTOR
    session.flush()


def _list_open_reviews(session: Session, planting_plan_id: int) -> list[ReviewSummary]:
    reviews = list(
        session.scalars(
            select(ReviewRequest)
            .where(ReviewRequest.planting_plan_id == planting_plan_id)
            .where(ReviewRequest.status == "open")
            .order_by(ReviewRequest.id.asc()),
        ),
    )
    task_intents = {
        item.id: item
        for item in session.scalars(
            select(TaskIntent).where(TaskIntent.planting_plan_id == planting_plan_id).order_by(TaskIntent.id.asc())
        )
    }
    return [
        ReviewSummary(
            id=int(item.id),
            review_type=item.review_type,
            task_subtype=task_intents.get(item.source_entity_id).task_subtype
            if item.source_entity_type in {"task_intent", "cf_task_intent"} and item.source_entity_id in task_intents
            else None,
            title=item.title,
            status=item.status,
        )
        for item in reviews
    ]


def _serialize_summary(summary: BootstrapSummary) -> dict[str, Any]:
    data = asdict(summary)
    data["next_step"] = {
        "resolved_by_examples": ["reviewer-demo", "联调复核员"],
        "review_request_ids": {
            item.task_subtype or item.review_type: item.id for item in summary.open_reviews
        },
    }
    return data


def _sync_id_sequence(session: Session, table_name: str) -> None:
    session.execute(
        text(
            f"""
            select setval(
                pg_get_serial_sequence('{table_name}', 'id'),
                coalesce((select max(id) from {table_name}), 1),
                true
            )
            """
        ),
    )


if __name__ == "__main__":
    main()
